//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratoslaborales
    {
        public int idcontrato { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<int> idarl { get; set; }
        public Nullable<int> idcargo { get; set; }
        public Nullable<int> idtipodocumento { get; set; }
        public Nullable<decimal> numerodocumento { get; set; }
        public string primerapellido { get; set; }
        public string segundoapellido { get; set; }
        public string primernombre { get; set; }
        public string segundonombre { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public Nullable<decimal> salario { get; set; }
        public string usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
    
        public virtual arl arl { get; set; }
        public virtual cargos cargos { get; set; }
        public virtual estados estados { get; set; }
        public virtual tipodocumento tipodocumento { get; set; }
    }
}
