//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedadesnomina
    {
        public int idnovedadnomina { get; set; }
        public string periodolaborado { get; set; }
        public Nullable<decimal> horaslaboradas { get; set; }
        public Nullable<decimal> horaextradiurna { get; set; }
        public Nullable<decimal> horaextranocturna { get; set; }
        public Nullable<decimal> horaextradominical { get; set; }
        public Nullable<decimal> horaextrafestiva { get; set; }
        public Nullable<decimal> descuentos { get; set; }
        public string usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
    }
}
