//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebatecnicaEntities : DbContext
    {
        public pruebatecnicaEntities()
            : base("name=pruebatecnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arl> arl { get; set; }
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<contratoslaborales> contratoslaborales { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<novedadesnomina> novedadesnomina { get; set; }
        public virtual DbSet<tipodocumento> tipodocumento { get; set; }
    }
}
